"""发版纯业务逻辑 —— 无需 Qt / PySide6 依赖，可供 CLI 或自动化流程直接调用。"""

import re
from pathlib import Path

import requests

from ._shared import (
    MANIFEST_FILE_PATH,
    MANIFEST_REPO,
    OWNER_REPO,
    REQUEST_TIMEOUT,
    fetch_json_from_repo,
    get_default_branch,
    get_sha256,
    github_headers,
    put_json_to_repo,
    resolve_token,
)


def _detect_version() -> str:
    """从 EasiAuto 包读取当前版本号。"""
    try:
        from EasiAuto import __version__

        return str(__version__)
    except ImportError:
        return ""


def collect_release_assets(dist_dir: Path, version: str) -> list[Path]:
    """在 *dist_dir* 中查找匹配 *version* 的 zip 构建产物。"""
    pattern = re.compile(rf"^EasiAuto_v{re.escape(version)}(?:_lite)?\.zip$", re.IGNORECASE)
    files = [path for path in dist_dir.iterdir() if path.is_file() and pattern.match(path.name)]
    files.sort(key=lambda path: path.name)
    if not files:
        raise ValueError(
            f"在目录 {dist_dir} 中未找到版本 {version} 的构建产物，"
            f"命名应为 EasiAuto_v{version}.zip 或 EasiAuto_v{version}_lite.zip"
        )
    return files


def generate_release_body(
    desc: str | None,
    highlights: list[dict],
    others: list[str],
) -> str:
    """生成 GitHub Release 的 Markdown 正文。"""
    body_parts = []

    if desc:
        body_parts.append(f"## 📝 说明\n\n{desc}\n")

    if highlights:
        body_parts.append("## ✨ 亮点功能\n")
        for hl in highlights:
            name = hl.get("name", "").strip()
            description = hl.get("description", "").strip()
            if name:
                body_parts.append(f"- **{name}**: {description}")
        body_parts.append("")

    if others:
        body_parts.append("## 🛠️ 其他更改\n")
        for item in others:
            if item.strip():
                body_parts.append(f"- {item.strip()}")
        body_parts.append("")

    body_parts.append("---")
    body_parts.append("Generated by EasiAuto Release Tool")
    return "\n".join(body_parts)


def create_github_release(version: str, body: str, is_dev: bool, is_draft: bool = False) -> dict:
    """在 GitHub 上创建或更新 Release，返回 Release 信息 JSON。"""
    token = resolve_token()
    if not token:
        raise ValueError("未找到 TOKEN")

    headers = github_headers(token)

    # 先尝试获取已有 Release
    get_url = f"https://api.github.com/repos/{OWNER_REPO}/releases/tags/v{version}"
    resp = requests.get(get_url, headers=headers, timeout=REQUEST_TIMEOUT)
    if resp.status_code == 200:
        release_data = resp.json()
        release_id = release_data["id"]
        update_url = f"https://api.github.com/repos/{OWNER_REPO}/releases/{release_id}"

        data = {
            "name": f"EasiAuto v{version}",
            "body": body,
            "draft": is_draft,
            "prerelease": is_dev,
        }
        resp = requests.patch(update_url, headers=headers, json=data, timeout=REQUEST_TIMEOUT)
        resp.raise_for_status()
        return resp.json()

    # 新建 Release
    url = f"https://api.github.com/repos/{OWNER_REPO}/releases"
    data = {
        "tag_name": f"v{version}",
        "target_commitish": get_default_branch(OWNER_REPO, token),
        "name": f"EasiAuto v{version}",
        "body": body,
        "draft": is_draft,
        "prerelease": is_dev,
    }
    resp = requests.post(url, headers=headers, json=data, timeout=REQUEST_TIMEOUT)
    resp.raise_for_status()
    return resp.json()


def upload_asset(upload_url_template: str, file_path: Path, release_assets: list[dict]):
    """上传单个资产文件到 GitHub Release，如同名文件已存在则先删除。"""
    token = resolve_token()
    if not token:
        raise ValueError("未找到 TOKEN")

    filename = file_path.name
    existing_asset = next((asset for asset in release_assets if asset.get("name") == filename), None)
    if existing_asset and existing_asset.get("id"):
        delete_url = f"https://api.github.com/repos/{OWNER_REPO}/releases/assets/{existing_asset['id']}"
        delete_resp = requests.delete(delete_url, headers=github_headers(token), timeout=REQUEST_TIMEOUT)
        delete_resp.raise_for_status()

    base_upload_url = upload_url_template.split("{", maxsplit=1)[0]
    upload_url = f"{base_upload_url}?name={filename}"

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/zip",
    }

    with file_path.open("rb") as f:
        resp = requests.post(upload_url, headers=headers, data=f, timeout=REQUEST_TIMEOUT)
    resp.raise_for_status()


def update_manifest(
    *,
    dist_dir: Path,
    version: str,
    is_dev: bool,
    confirm_required: bool,
    desc: str | None = None,
    highlights: list[dict],
    others: list[str],
    push_to_beta: bool = False,
):
    """获取远端 manifest → 追加版本条目 → 推送回仓库。"""
    token = resolve_token()
    if not token:
        raise ValueError("未找到 Token")

    manifest, sha = fetch_json_from_repo(MANIFEST_REPO, MANIFEST_FILE_PATH, token)

    downloads = []
    for file_path in collect_release_assets(dist_dir, version):
        channel = "lite" if "_lite" in file_path.stem.lower() else "default"
        downloads.append(
            {
                "channel": channel,
                "url": f"https://github.com/{OWNER_REPO}/releases/download/v{version}/{file_path.name}",
                "sha256": get_sha256(file_path),
            }
        )

    new_version_entry = {
        "is_dev": is_dev,
        "confirm_required": confirm_required,
        "description": desc,
        "highlights": highlights,
        "others": others,
        "downloads": downloads,
    }

    manifest["versions"][version] = new_version_entry

    if is_dev:
        manifest["latest_dev"] = version
    else:
        manifest["latest"] = version
        if push_to_beta:
            manifest["latest_dev"] = version

    put_json_to_repo(
        MANIFEST_REPO,
        MANIFEST_FILE_PATH,
        sha,
        manifest,
        f"Release {version}",
        token,
    )


def do_full_release(
    *,
    dist_dir: Path,
    version: str,
    is_dev: bool,
    confirm_required: bool,
    desc: str | None = None,
    highlights: list[dict],
    others: list[str],
    push_to_beta: bool = False,
    is_draft: bool = False,
) -> str:
    """执行完整的发版流程：创建 GitHub Release → 上传资产 → 更新清单。

    返回成功消息字符串；失败时抛出异常。
    """
    token = resolve_token()
    if not token:
        raise ValueError("未找到 GitHub Token，请设置 RELEASE_PAT 环境变量")

    print(f"📦 收集 {dist_dir} 中的构建产物 (版本 {version})...")
    assets = collect_release_assets(dist_dir, version)
    print(f"   找到 {len(assets)} 个文件: {[a.name for a in assets]}")

    body = generate_release_body(desc, highlights, others)

    print(f"🚀 创建/更新 GitHub Release v{version} ...")
    release_info = create_github_release(version=version, body=body, is_dev=is_dev, is_draft=is_draft)
    upload_url_template = release_info["upload_url"]
    release_assets_list = release_info.get("assets", [])

    for file_path in assets:
        print(f"⬆️  上传 {file_path.name} ...")
        upload_asset(upload_url_template, file_path, release_assets_list)

    print("📝 更新远端 manifest ...")
    update_manifest(
        dist_dir=dist_dir,
        version=version,
        is_dev=is_dev,
        confirm_required=confirm_required,
        desc=desc,
        highlights=highlights,
        others=others,
        push_to_beta=push_to_beta,
    )

    return f"版本 {version} 发版成功！"
